CUE4Parse-Conversion/Meshes/MeshExporter.cs

Vertex normals in psk/pskx files, needs updated importer addons for 3D softwares.
Might be better to force extension to pskx as this chunk is not part of the standard.

VTXNORMS chunk

---

CUE4Parse/UE4/Objects/Core/Math/FColor.cs

[Since UE3, FColor has different memory layout - BGRA. -- /UEViewer/.../UnCore.h#L2462-L2465](https://github.com/gildor2/UEViewer/blob/master/Unreal/UnCore.h#L2462-L2465)
&
[/UnrealEngine/.../Color.h#L413-L421](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Core/Public/Math/Color.h#L413-L421)
Vertex colors:

FColor RGBA -> BGRA

---

CUE4Parse-Conversion/Animations/AnimExporter.cs
CUE4Parse-Conversion/Animations/PSA/VScaleAnimKey.cs
CUE4Parse-Conversion/Constants.cs

Exporting scale keys.
https://github.com/Befzz/blender3d_import_psk_psa/pull/84
https://user-images.githubusercontent.com/57007485/166123275-b1d5f6fb-29d1-4b85-91f9-149073e007f3.mp4

Scale keys export with PSA (SCALEKEYS chunk)

---

CUE4Parse/UE4/Assets/Exports/Animation/AnimCompressionTypes.cs

CompressedByteStream is read after CompressedScaleOffsets in 4.23-4.24, but before CompressedTrackOffsets in 4.25 and later.
SerializeCompressedData2: https://github.com/gildor2/UEViewer/blob/e879659ab154930630279ba8c10ed0fd022f27e6/Unreal/UnrealMesh/UnAnim4.cpp#L1362-L1365
SerializeCompressedData3: https://github.com/gildor2/UEViewer/blob/e879659ab154930630279ba8c10ed0fd022f27e6/Unreal/UnrealMesh/UnAnim4.cpp#L1493-L1496

Fix FUECompressedAnimData.CompressedByteStream being read too early in 4.23-4.24

---

CUE4Parse/UE4/Readers/FArchive.cs

This enables ability to parse large FiBData blocks. Since these blocks can be essentially an arbitrary size may be it would be better to introduce default parameter for the `ReadFString` function that would be used to ignore in-place limits. Since it is a default one, it will keep compatibility in tact and only requires internal changes to library's inheriting members.

Increase the default FString limits

---

CUE4Parse/UE4/Assets/Exports/Component/StaticMesh/FInstancedStaticMeshInstanceData.cs
CUE4Parse/UE4/Objects/Core/Math/FQuat.cs
CUE4Parse/UE4/Objects/Core/Math/FTransform.cs
CUE4Parse/UE4/Objects/Core/Math/Matrix.cs

This PR fixes the incorrect rotation values in FInstancedStaticMeshInstanceData by removing scaling from the transformation matrix before getting the rotation data.
`ExtractScaling()` (for FMatrix) and `SetFromMatrix()` (for FTransform) methods were added and FMatrix => FQuat ( `ToQuat()` ) was fixed.
An indexer for FMatrix was also added.
Fast inverse square root was replaced as it's not sufficient here.

Fixing FInstancedStaticMeshInstanceData

---

CUE4Parse/UE4/Objects/UObject/FPackageFileSummary.cs
CUE4Parse/UE4/Versions/EGame.cs
CUE4Parse/UE4/Versions/ObjectVersion.cs

Implementation for ObjectVersion ADD_SOFTOBJECTPATH_LIST in FPackageFileSummary
Reference:
https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/CoreUObject/Private/UObject/PackageFileSummary.cpp#L217
I couldn't figure out how the values are used, but with this they will at least be read properly and not mess up the rest of the summary
I think at least, I haven't been able to test it, but I think it looks right based on the UE source code

ADD_SOFTOBJECTPATH_LIST in FPackageFileSummary

---

CUE4Parse-Conversion/Meshes/MeshExporter.cs

fixes index out of bounds on meshes like FortniteGame/Content/Characters/Player/Female/Medium/Heads/F_MED_CAU_Emmy_Head_01/Meshes/F_MED_CAU_Emmy_Head_01_zom

fix morph export when lod number out of bounds

---

CUE4Parse/UE4/Objects/Core/i18N/FText.cs

Allows LocalizedString to be set when explicitly making an FText, if the localized string is null or empty it defaults to SourceString.
Main reason was to fix the Text property of FText being empty since the localized string was always set to string.Empty when creating an FTextHistory.Base

Allow Explicit LocalizedString Definition

---

CUE4Parse/UE4/Assets/Exports/StaticMesh/UStaticMesh.cs
CUE4Parse/UE4/Versions/EGame.cs

This change fixes compatibility with Hogwarts Legacy game (based on Unreal Engine 4.27.2)
where this game's static meshes contain additional 64 bytes of data of (as of now) unkonwn purpose. 
Just skipping them works and the models are able to be exported and previewed just fine, for details see issue https://github.com/4sval/FModel/issues/357 where I originally raised this issue.
This commit was tested working with latest version of FModel on dev branch commit #[f3c1103](https://github.com/4sval/FModel/commit/f3c1103b0cf57ffd91bb688297b18829dfd65d0a)

Fix loading of static meshes from Hogwarts Legacy

---

CUE4Parse-Conversion/Animations/AnimExporter.cs
CUE4Parse-Conversion/IExporter.cs
CUE4Parse-Conversion/Meshes/MeshExporter.cs

It doesn't make any sense to change the exported mesh/anim's name to something different when many processes of modding pipelines relies on having the name be the same as the original, unless it needs to export multiple versions of the same asset, i.e. LODs or sequence indexes. 
@MinshuG any objections to updating this? If needs be (for backward compatibility reasons or whatever), I can add an option to have the new behaviour disabled by default, just let me know.
I also added an option for exporting materials, as currently it is always set to true with no way to change it...

Exporter QoL

---

CUE4Parse-Conversion/Animations/AnimExporter.cs

This fixes https://github.com/FabianFG/CUE4Parse/issues/103.

Fix for PSA sequences incorrectly reporting the FirstRawFrame

---

CUE4Parse/UE4/Objects/Core/i18N/FText.cs

due to mixing up Dictionary `Capacity` with `Count`

fix not parsing of FTextHistory.NamedFormat arguments

---

CUE4Parse/FileProvider/AbstractFileProvider.cs
CUE4Parse/GameTypes/L2KD/Objects/FLegoGraphPartInstance.cs
CUE4Parse/UE4/Assets/Objects/UScriptStruct.cs

- Add support for `PartGraphInstance` Struct used in Lego 2K Drive
- Allow GameDisplayName to use alternate search if previous returned `{GameName} `

L2KD PartGraph

---

CUE4Parse/JsonConverters.cs
CUE4Parse/UE4/Assets/Objects/UScriptArray.cs
CUE4Parse/UE4/Readers/FArchive.cs

It causes the maps serialized as arrays instead of dictionaries.
Also added some checks to avoid CLR crashes and unnecessary creation of huge arrays.

UScriptMapConverter creating arrays instead of objects

---

CUE4Parse/UE4/Assets/Objects/Properties/ByteProperty.cs
CUE4Parse/UE4/Versions/EGame.cs
CUE4Parse/UE4/Versions/VersionContainer.cs

Fixes #97 
It is possible that TMap can be overriden but automated TMap struct override dumpers did not find this, and dumping the entire game did not find any issues.

Fix for Potionomics TMap

---

CUE4Parse/JsonConverters.cs

It fixes the the object creation problem for Struct types in https://github.com/FabianFG/CUE4Parse/pull/124

Fix for StructProperty key/values for UScriptMapConverter serialization

---

CUE4Parse/UE4/Kismet/KismetExpression.cs

In FModel, the output of `EX_DynamicCast` contains the `Target` info twice. Looks like this happens because `EX_CastBase` already writes this information, so don't dump it again in `EX_DynamicCast`.

fix: Do not dump `Target` again for `EX_DynamicCast`

---

CUE4Parse-Conversion/Animations/UEFormat/UEAnim.cs
CUE4Parse/UE4/Assets/Exports/Animation/AnimCurveCompressionCodec_CompressedRichCurve.cs
CUE4Parse/UE4/Assets/Exports/Animation/AnimCurveTypes.cs
CUE4Parse/UE4/Assets/Exports/Animation/UAnimSequence.cs

**Summary**
When working on https://github.com/halfuwu/FortnitePorting/pull/42, I noticed through the debugger that all entries in `FPoseDataContainer`'s `Curves` were null.
This PR provides a small patch to ensure `Curves` in `FPoseDataContainer` is properly parsed. Interestingly though, this data is parsed without any issues when conerted to JSON through FModel.

Fixed parsing of `Curves` data in `PoseContainer`

---

CUE4Parse-Conversion/Meshes/MeshConverter.cs
CUE4Parse-Conversion/Meshes/PSK/ActorXMesh.cs
CUE4Parse-Conversion/Meshes/PSK/BoneInfluence.cs
CUE4Parse-Conversion/Meshes/PSK/CSkelMeshVertex.cs
CUE4Parse-Conversion/Meshes/UEFormat/UEModel.cs
CUE4Parse-Conversion/Meshes/glTF/Gltf.cs

This PR aims to remove the hardcoded limit of 4 bone weight influences.
I have tested it manually on a few skeletal meshes from a game that use 8 bone weight influences, and it seems to work.
However, I couldn't try out the glTF export, since it seems to be broken on the current master branch (throws a NullReferenceException when exporting)?

Remove hardcoded limit of 4 bone weight influences

---

CUE4Parse-Conversion/Textures/TextureDecoder.cs

Currently, a few textures in the Fortnite files are stored as UTexture2DArray objects, which pack multiple images into a single image with multiple layers.  For example, TA_Atlas_Figure_EyeAndLash_Char01 has 20 different textures packed into that single object.  
This PR adds a new "DecodeTextureArray()" method that decodes and returns an array of all textures contained in that object, and adds an optional "zLayer" parameter to the existing Decode() method which would allow for decoding a single layer instead of being locked to either the first layer or the entire set of layers

UTexture2DArray handling

---

CUE4Parse/UE4/Readers/FArchive.cs
CUE4Parse/UE4/Readers/FByteArchive.cs
CUE4Parse/UE4/Readers/FPointerArchive.cs
CUE4Parse/UE4/Readers/FStreamArchive.cs

Fail fast checks to prevent unnecessary array creations

Archive read size checks

---

CUE4Parse-Conversion/Animations/AnimConverter.cs
CUE4Parse-Conversion/Animations/UEFormat/UEAnim.cs
CUE4Parse/FileProvider/AbstractFileProvider.cs
CUE4Parse/UE4/Assets/Exports/Animation/AnimCompress_Constant.cs

- Supports exporting animations from Arc System Works games, which use a custom AnimCompress class.
- Supports exporting scale keyframes for games that don't use ACL.

Arc System Works game animation support, support for scale keyframes pre-ACL

---

CUE4Parse/JsonConverters.cs
CUE4Parse/UE4/Shaders/FSerializedShaderArchive_MarvelRivals.cs
CUE4Parse/UE4/Shaders/FShaderCodeArchive.cs

Marvel Rivals uses SHA-224 for its shader hashes (NOT shader map hashes though), and has an additional unknown 4 bytes afterwards.

Marvel Rivals shader archive support

---

CUE4Parse/UE4/Pak/Objects/FPakInfo.cs
CUE4Parse/UE4/Versions/EGame.cs

CUE4Parse already has support for ARK: Survival Evolved. This PR adds support for ARK: Survival Ascended which requires an additional 8 byte offset for pak files. 
Closes #197

[feat] add ARK Ascended game type & configure offsets

---

CUE4Parse/FileProvider/AbstractFileProvider.cs

In February, when `AbstractFileProvider` was rewritten, all of its virtual methods were removed or unmarked as virtual. This PR re-marks the equivelent methods as virtual again

Make AbstractFileProvider methods virtual again

---

CUE4Parse/UE4/Assets/Exports/Internationalization/FStringTable.cs

Hacky fix to fix loading datatables in Marvel Rivals.
This leaves data unread so a proper fix is maybe necessary.
i.e.
```
[13:30:15 WRN] Did not read StringTable correctly, 85 bytes remaining (11.66%)
[13:30:15 WRN] Did not read StringTable correctly, 85 bytes remaining (11.66%)
[13:30:15 WRN] Did not read StringTable correctly, 85 bytes remaining (11.66%)
[13:30:15 WRN] Did not read StringTable correctly, 89 bytes remaining (12.21%)
[13:30:15 WRN] Did not read StringTable correctly, 89 bytes remaining (12.21%)
[13:30:15 WRN] Did not read StringTable correctly, 89 bytes remaining (12.21%)
[13:30:15 WRN] Did not read StringTable correctly, 89 bytes remaining (12.24%)
[13:30:15 WRN] Did not read StringTable correctly, 89 bytes remaining (12.24%)
[13:30:15 WRN] Did not read StringTable …
```

Fix Marvel Rivals StringTables

---

CUE4Parse/GameTypes/MindsEye/Encryption/Aes/MindsEyeAes.cs

This is more an exercise for myself trying to figure out what they changed in the encryption. Because of some design choices in the codebase, this may or may not be faster than the current implementation (and I don't have anything set up for benchmarking).
* `Aes.Decrypt()` recreates a new transform every time it's called, which is not great considering the key's the same across all files (in this game).
* Hardcoded key schedule removed, so you lose that static key schedule, but on the other hand since it goes through the framework's AES implementation, maybe it could take advantage of hardware accelerated AES instructions? Plus if the key changes, the code does not have to be updated (unless they also change the custom data mangling).
* `FAesKey` converts bytes to string every time it's …

Simplify MindsEye custom AES decrypt implementation

---

CUE4Parse/UE4/Assets/Exports/Material/UMaterialInstance.cs

below 4.19 StaticParameters is not a uproperty, this means that in UObject.WriteJson, StaticParameters won't be written during the writing of uproperties. this PR addresses this issue by writing the staticparameters if necessary in UMaterialInterface.WriteJson
note: this means that they wont be under the properties json object, so anyone wishing to parse the json will have to watch out for that.

Fix staticparameters not showing on ue versions below 4.19

---

CUE4Parse-Conversion/Animations/UEFormat/UEAnim.cs
CUE4Parse/UE4/Assets/Readers/FKismetArchive.cs
CUE4Parse/UE4/Kismet/EExprToken.cs
CUE4Parse/UE4/Kismet/KismetExpression.cs
CUE4Parse/UE4/Objects/UObject/BlueprintDecompiler/BlueprintDecompilerUtils.cs

Changelog:
- Animations using AnimCompress_Constant (Arc System Works custom compression) will export properly.
- 2XKO has a custom script bytecode instruction for fixed-point integers. As the instruction ID doesn't overlap with any other games (0xFD), I did not make a custom game configuration. If needed, please change.

Arc System Works animations, 2XKO script bytecode
